version: '3'

services:

    terraform_docker:
        image: datafuel/terraform_docker
        container_name: terraform_docker
        build:
            context: .
        environment:
            - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
        volumes:
            - ./modules:/opt/workspace/modules
            - ./environments:/opt/workspace/environments
        stdin_open: true # docker run -i
        tty: true