version: '3'

services: 

    devops:
        build:
            context: .
            args: 
                - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
                - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
        image: dockerisedenvs/iac_devops