version: '3'

services:

    devops:
        image: dockerisedenvs/iac_devops
        build:
            context: .
        environment:
            - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
        volumes:
            - ./modules:/opt/workspace/modules
            - ./devops:/opt/workspace/devops
        stdin_open: true # docker run -i
        tty: true